# Generated by Django 4.0.3 on 2022-04-09 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchSizeNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(null=True)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.size')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остаток',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.AddField(
            model_name='merch',
            name='merch_size_num',
            field=models.ManyToManyField(null=True, to='main.merchsizenum'),
        ),
    ]
