# Generated by Django 4.0.3 on 2022-04-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_merch_merch_size_num_merch_merch_size_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merch',
            name='merch_size_num',
        ),
        migrations.AddField(
            model_name='merch',
            name='merch_size_num',
            field=models.ManyToManyField(null=True, to='main.merchsizenum'),
        ),
    ]
