# Generated by Django 4.0.3 on 2022-04-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_merch_merch_size_num_merchsizenum_merch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchsizenum',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchsizenum',
            name='merch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merch_size_num', to='main.merch'),
        ),
    ]
