# Generated by Django 4.0.3 on 2022-04-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merchsizenum_title_alter_merchsizenum_merch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchsizenum',
            name='title',
        ),
    ]
