# Generated by Django 4.0.3 on 2022-04-09 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_merchsizenum_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchsizenum',
            old_name='num',
            new_name='count',
        ),
    ]
