# Generated by Django 4.0.3 on 2022-04-10 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_orders_user_orders_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='basket_value',
            new_name='basket_coast',
        ),
    ]
