# Generated by Django 4.0.3 on 2022-04-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_orders_merch_size_orders_size_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='size_count',
            field=models.IntegerField(),
        ),
    ]
